In [18]:
import numpy as np
import pandas as pd

## 5) Crear un arreglo de Numpy
Para poder crear una arreglo de Numpy, primero se debe importar la libreria numpy y utilizar la función array().

### `numpy.array`

La función `numpy.array` en Numpy se utiliza para crear un arreglo N-dimensional.

#### Sintaxis

```python
numpy.array(object)
```



##### Parametros

- `object`: `array_like`
    - Un objeto que expone la interfaz de arreglo, o cualquier (secuencia) de objetos que puedan ser convertidos a un arreglo.


```python
numpy.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
```

<details>
  <summary>Resto de parametros</summary>
  
  - `dtype`: `data-type`, *opcional*
    - El tipo de datos deseado para el arreglo. Si no se especifica, se infiere del tipo de datos de los elementos en el objeto.
  - `copy`: `bool`, *opcional*
    - Si es True (por defecto), se copia el objeto. Si es False, se puede evitar la copia si no es necesario.
  - `order`: `{'K', 'A', 'C', 'F'}`, *opcional*
    - Especifica el orden de la memoria:
      - 'C' para filas principales (C-order),
      - 'F' para columnas principales (Fortran-order),
      - 'A' ('Any') para filas principales a menos que el objeto de entrada sea Fortran contiguous (entonces se usa Fortran-order),
      - 'K' ('Keep') para mantener el orden de los elementos en la memoria lo más posible (por defecto).
  - `subok`: `bool`, *opcional*
    - Si es True, las subclases se pasan a través; de lo contrario, el resultado será forzado a ser una clase base de arreglo.
  - `ndmin`: `int`, *opcional*
    - Especifica el número mínimo de dimensiones que debe tener el arreglo resultante.
</details>


In [21]:
arr1 = np.array([1, 2, 3, 4, 5])
print(np.ndim(arr1))

1


## 6) Arreglo de dos dimensiones

$$
\begin{bmatrix} 
1 & 2 & 3 \\ 
4 & 5 & 6 
\end{bmatrix}
FilasxColumnas
$$

$$
\begin{bmatrix}
1 & 2 & 3 & 4 & 5 & 6
\end{bmatrix}
$$

In [ ]:
arr2 = np.array([[1, 2, 3], 
                 [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])


## 7) Comprobacion del numero de dimensiones de un arreglo 
### `numpy.ndim`

La función `numpy.ndim` se utiliza para obtener el número de dimensiones (o ejes) de un arreglo.

#### Sintaxis

``` python
numpy.ndim(a)
```

In [11]:
np.ndim(arr2)

2

## 8) Sintaxis para imprimir el primer elemento de un arreglo
`Arreglo` = [1, 2, 3, 4, 5]

`Indices` = 0, 1, 2, 3, 4

In [12]:
print(arr1[0])

1


## 9) Sintaxis correcta para imprimir el numero 8 de una matriz

In [25]:
arr = np.array([[1,2,3,4,5], 
                [6,7,8,9,10]])
arr[1, 2]

np.int64(8)

## 10) Sintaxis correcta para imprimir los numeros `[3, 4, 5]` de la matriz `np.array([1, 2, 3, 4, 5, 6, 7])`

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[2:5]
'''
2:5 representa el rango de indices que se desean seleccionar del array
2 es el indice inicial y 5 es el indice final, pero no se incluye el indice final
'''

array([3, 4, 5])

## 11) Metodo para unir dos o mas arreglos 
### `numpy.concatenate`

La función `numpy.concatenate` se utiliza para unir dos o más arreglos a lo largo de un eje especificado.

### Sintaxis

```python
numpy.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
```

### Parametros
- `a1, a2, ...`: `sequence of array_like`
  - Los arreglos que se van a concatenar. Todos deben tener la misma forma, excepto en la dimensión especificada por axis.

<details>
  <summary>Resto de parametros</summary>

  - `axis`: `int`, opcional
    - El eje a lo largo del cual se concatenan los arreglos. El valor predeterminado es 0.
  - `out`: `ndarray`, opcional
    - Si se proporciona, el resultado se coloca en este arreglo.
  - `dtype`: `dtype`, opcional
    - Si se proporciona, el tipo de datos del resultado.
  - `casting`: `{'no', 'equiv', 'safe', 'same_kind', 'unsafe'}`, opcional
    - Reglas de casting para la conversión de tipos de datos.

</details>


In [17]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
np.concatenate((arr1, arr2))

array([1, 2, 3, 4, 5, 6])

### Ejemplo de `numpy.concatenate` con diferentes ejes

In [21]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
concatenado_eje_0 = np.concatenate((arr1, arr2), axis=0)
print(concatenado_eje_0)
# Salida:
# [[1 2]
#  [3 4]
#  [5 6]
#  [7 8]]


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [23]:
concatenado_eje_1 = np.concatenate((arr1, arr2), axis=1)
print(concatenado_eje_1)
# Salida:
# [[1 2 5 6]
#  [3 4 7 8]]

[[1 2 5 6]
 [3 4 7 8]]


## 12) Devolver un número aleatorio entre 0 y 100 con random de Numpy
### `numpy.random.randint`

La función `numpy.random.randint` se utiliza para generar números enteros aleatorios dentro de un rango especificado.

### Sintaxis

```python
numpy.random.randint(low, high=None, size=None, dtype=int)
```
### Parametros
- `low`: `int`
  - El límite inferior (inclusive) del rango de los números aleatorios generados.

<details>
  <summary>Resto de parametros</summary>
  
  - `high`: `int`, opcional
    - El límite superior (exclusivo) del rango de los números aleatorios generados. Si no se especifica, el rango será [0, low).
  - `size`: `int or tuple of ints`, opcional
    - La forma del arreglo de salida. Si se especifica un solo entero, se generará un arreglo unidimensional de esa longitud. Si se especifica una tupla, se generará un arreglo con esa forma.
  - `dtype`: `dtype`, opcional
    - El tipo de datos del arreglo de salida. El valor predeterminado es int.
</details>



In [ ]:
np.random.randint(100)

12

## 14) Uso de `random.normal` para devolver una distribución normal de datos de 1000 numeros, concetrados al rededor del numero 50 y una desviación estandar de 0.2

### `numpy.random.normal`

La función `numpy.random.normal` se utiliza para generar números aleatorios siguiendo una distribución normal (gaussiana).

#### Sintaxis

```python
numpy.random.normal(loc=0.0, scale=1.0, size=None)
```

### Parametros
    
  - `loc`: `float or array_like of floats`
    - La media (o centro) de la distribución. El valor predeterminado es 0.0.
  - `scale`: `float or array_like of floats`
    - La desviación estándar (o ancho) de la distribución. El valor predeterminado es 1.0.
  - `size`: `int or tuple of ints`, opcional
    - La forma del arreglo de salida. Si se especifica un solo entero, se generará un arreglo unidimensional de esa longitud. Si se especifica una tupla, se generará un arreglo con esa forma. Si no se especifica, se devolverá un solo valor.

In [3]:
np.random.normal(size=1000, loc=50, scale=0.2)

array([50.13881749, 49.90462035, 50.02524587, 49.86813976, 49.99548126,
       49.98548772, 50.07709024, 49.96141501, 49.94188076, 49.97490456,
       49.81985227, 49.88065419, 50.35000233, 50.07397546, 49.89833934,
       49.67730746, 50.01041093, 50.24111551, 49.83608885, 49.76274716,
       50.26532047, 49.83617344, 49.99952354, 49.87992225, 50.30702853,
       49.970387  , 49.94540599, 50.12388874, 50.07846714, 50.29888564,
       49.85780435, 50.3759549 , 49.81617909, 50.21211513, 50.19439849,
       49.75377095, 49.91411444, 49.93624731, 49.5779064 , 50.34755062,
       50.37483096, 50.00509895, 49.95804819, 49.88382493, 49.72328855,
       49.99182165, 49.96211046, 49.97806732, 50.07641573, 50.29151492,
       50.16383078, 50.01890408, 50.17909027, 49.59696507, 49.91252557,
       50.33424793, 50.18050881, 50.2780442 , 49.86352631, 50.23664732,
       49.66616819, 50.28725809, 50.31175481, 50.05015338, 50.0333565 ,
       50.24835123, 50.10594617, 50.16838916, 50.02148231, 49.98

## 15) Sintaxis correcta par sumar los numeros de dos arreglos.

### `numpy.add`

La función `numpy.add` se utiliza para sumar dos arreglos elemento por elemento.

#### Sintaxis

```python
numpy.add(x1, x2, out=None, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
```

#### Parametros

- `x1, x2`: `array_like`
  - Los arreglos o escalares que se van a sumar. Deben tener la misma forma o ser transmisibles (broadcastable) a una forma común.

<details>
  <summary>Resto de parametros</summary>
  
  - `out`: `ndarray, None, or tuple of ndarray and None`, opcional
    - Un lugar donde almacenar el resultado. Si se proporciona, debe tener una forma que el resultado pueda transmitir. Si no se especifica, se devuelve un nuevo arreglo.
  - `where`: `array_like`, opcional
    - Este valor es transmitido a través de la entrada. El valor predeterminado es True.
  - `casting`: `{'no', 'equiv', 'safe', 'same_kind', 'unsafe'}`, opcional
    - Reglas de casting para la conversión de tipos de datos. El valor predeterminado es 'same_kind'.
  - `order`: `{'C', 'F', 'A', 'K'}`, opcional
    - Especifica el orden de la memoria del resultado. El valor predeterminado es 'K'.
  - `dtype`: `data-type`, opcional
    - El tipo de datos del resultado. Si no se especifica, se infiere del tipo de datos de los operandos.
  - `subok`: `bool`, opcional
    - Si es `True`, las subclases se pasan a través; de lo contrario, el resultado será forzado a ser una clase base de arreglo.
</details>

In [4]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
np.add(arr1, arr2)

array([ 7,  9, 11, 13, 15])

## 16) Sintaxis para restar los numeros de dos arreglos 
### `numpy.subtract`

La función `numpy.subtract` se utiliza para restar los elementos de dos arreglos, elemento por elemento.

#### Sintaxis

```python
numpy.subtract(x1, x2, out=None, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
```

#### Parámetros

- **x1, x2**: array_like
    - Los arreglos o escalares que se van a restar. Deben tener la misma forma o ser transmisibles (broadcastable) a una forma común.

<details>
  <summary>Resto de parametros</summary>
  
- **out**: ndarray, None, or tuple of ndarray and None, opcional
    
    - Un lugar donde almacenar el resultado. Si se proporciona, debe tener una forma que el resultado pueda transmitir. Si no se especifica, se devuelve un nuevo arreglo.
- **where**: array_like, opcional
    
    - Este valor es transmitido a través de la entrada. El valor predeterminado es `True`.
- **casting**: {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, opcional
    
    - Reglas de casting para la conversión de tipos de datos. El valor predeterminado es 'same_kind'.
- **order**: {'C', 'F', 'A', 'K'}, opcional
    
    - Especifica el orden de la memoria del resultado. El valor predeterminado es 'K'.
- **dtype**: data-type, opcional
    
    - El tipo de datos del resultado. Si no se especifica, se infiere del tipo de datos de los operandos.
- **subok**: bool, opcional
    
    - Si es `True`, las subclases se pasan a través; de lo contrario, el resultado será forzado a ser una clase base de arreglo
</details>

In [14]:
np.subtract(arr2, arr1)

array([5, 5, 5, 5, 5])

## 17) Redondear decimales en Numpy

### `numpy.fix`

La función `numpy.fix` redondea los elementos del arreglo hacia cero, eliminando la parte decimal.

#### Sintaxis

```python
numpy.fix(x, out=None)
```

#### Parámetros

- **x**: array_like
  - Entrada del arreglo.
  
- **out**: ndarray, opcional
  - Un lugar donde almacenar el resultado. Si se proporciona, debe tener una forma que el resultado pueda transmitir. Si no se especifica, se devuelve un nuevo arreglo.

### `numpy.trunc`

La función `numpy.trunc` trunca los decimales, eliminando la parte decimal.

#### Sintaxis

```python
numpy.trunc(x, out=None)
```

#### Parámetros

- **x**: array_like
  - Entrada del arreglo.
  
- **out**: ndarray, opcional
  - Un lugar donde almacenar el resultado. Si se proporciona, debe tener una forma que el resultado pueda transmitir. Si no se especifica, se devuelve un nuevo arreglo.



### `numpy.around`

La función `numpy.around` se utiliza para redondear los elementos de un arreglo a un número especificado de decimales.

#### Sintaxis

```python
numpy.around(a, decimals=0, out=None)
```

#### Parámetros

- **a**: array_like
  - Entrada del arreglo que se va a redondear.
  
- **decimals**: int, opcional
  - Número de decimales a los que se redondearán los elementos. El valor predeterminado es 0. Si es negativo, se redondea a la izquierda del punto decimal.
  
- **out**: ndarray, opcional
  - Un lugar donde almacenar el resultado. Si se proporciona, debe tener una forma que el resultado pueda transmitir. Si no se especifica, se devuelve un nuevo arreglo.

In [15]:
a = np.array([1.5, -2.5, 3.7, -4.7])

# Redondear hacia cero
resultado = np.fix(a)
print(resultado)  # Salida: [ 1. -2.  3. -4.]


b = np.array([1.5, -2.5, 3.7, -4.7])

# Truncar los decimales
resultado = np.trunc(b)
print(resultado)  # Salida: [ 1. -2.  3. -4.]


c = np.array([1.23456, 2.34567, 3.45678])

# Redondear a 2 decimales
resultado = np.around(c, decimals=2)
print(resultado)  # Salida: [1.23 2.35 3.46]

# Redondear a -1 decimales (redondeo a la decena más cercana)
d = np.array([15, 25, 35])
resultado = np.around(d, decimals=-1)
print(resultado)  # Salida: [20 30 40]

[ 1. -2.  3. -4.]
[ 1. -2.  3. -4.]
[1.23 2.35 3.46]
[20 20 40]


## 18) Respuesta de la suma acumulativa en Numpy
### `numpy.cumsum`

La función `numpy.cumsum` se utiliza para calcular la suma acumulativa de los elementos a lo largo de un eje especificado.

#### Sintaxis

```python
numpy.cumsum(a, axis=None, dtype=None, out=None)
```

#### Parámetros

- **a**: array_like
  - Entrada del arreglo.
  
- **axis**: int, opcional
  - El eje a lo largo del cual se calcula la suma acumulativa. Si no se especifica, se calcula la suma acumulativa de todos los elementos del arreglo.
  
- **dtype**: dtype, opcional
  - El tipo de datos del resultado. Si no se especifica, se utiliza el tipo de datos del arreglo de entrada.
  
- **out**: ndarray, opcional
  - Un lugar donde almacenar el resultado. Si se proporciona, debe tener una forma que el resultado pueda transmitir. Si no se especifica, se devuelve un nuevo arreglo.

## Valor de retorno

- **cumsum**: ndarray
  - Un nuevo arreglo con la suma acumulativa de los elementos a lo largo del eje especificado. Si `out` se proporciona, se devuelve una referencia a `out`.

In [17]:
arr = np.array([1,2,3])
print(np.cumsum(arr))

[1 3 6]


## 19) Sintaxis para crear una serie de pandas a partir de una lista

### `pd.Series`

La clase `pd.Series` en pandas se utiliza para crear una serie unidimensional que puede contener cualquier tipo de datos (enteros, flotantes, cadenas, etc.).

### Sintaxis

```python
pd.Series(data=None, index=None, dtype=None, name=None, copy=False)
```

#### Parámetros

- **data**: array-like, iterable, dict, or scalar value
  - Los datos que se utilizarán para crear la serie. Puede ser una lista, un diccionario, un valor escalar, etc.
  
- **index**: array-like or Index (opcional)
  - Los índices para los datos. Si no se proporciona, se generará un índice predeterminado que va de 0 a N-1.
  
- **dtype**: dtype (opcional)
  - El tipo de datos para la serie. Si no se especifica, se inferirá del tipo de datos de `data`.
  
- **name**: str (opcional)
  - El nombre de la serie.
  
- **copy**: bool (opcional)
  - Si es `True`, se copia `data`. El valor predeterminado es `False`.

In [19]:
mylist = [1, 2, 3, 4, 5]

# Crear una Series de pandas a partir de la lista
serie = pd.Series(mylist)
serie

0    1
1    2
2    3
3    4
4    5
dtype: int64