In [19]:
import tensorflow as tf
print("GPU Disponible: ", tf.config.list_physical_devices('GPU'))

GPU Disponible:  []


In [4]:
import numpy as np

print("Version de Tensorflow: ", tf.__version__)

Version de Tensorflow:  2.18.0


In [6]:
a = np.array([1, 2, 3], dtype=np.int32)
b = [4, 5, 6]

t_a = tf.convert_to_tensor(a)
t_b = tf.convert_to_tensor(b)

print("Tensor t_a: ", t_a)
print("Tensor t_b: ", t_b)

Tensor t_a:  tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Tensor t_b:  tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [8]:
print("Es 'a' un tensor? ", tf.is_tensor(a))
print("Es 't_b' un tensor? ", tf.is_tensor(t_b))

Es 'a' un tensor?  False
Es 't_b' un tensor?  True


In [9]:
t_ones = tf.ones((2, 3))
print("Tensor de unos: ", t_ones)

print("Tensor de unos como array de numpy: ", t_ones.numpy())

Tensor de unos:  tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
Tensor de unos como array de numpy:  [[1. 1. 1.]
 [1. 1. 1.]]


In [10]:
const_tensor = tf.constant([1.2, 5, np.pi], dtype=tf.float32)
print("Tensor constante: ", const_tensor)

Tensor constante:  tf.Tensor([1.2       5.        3.1415927], shape=(3,), dtype=float32)


In [11]:
tensor_lleno = tf.fill((2, 3), 1)
print("Tensor lleno de unos: ", tensor_lleno)

Tensor lleno de unos:  tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


In [12]:
one_hot_tensor = tf.one_hot([0, 1, 2], 4)

print("Tensor one_hot: ", one_hot_tensor)

Tensor one_hot:  tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]], shape=(3, 4), dtype=float32)


In [13]:
t_a_new = tf.cast(t_a, tf.int64)
print("Nuevo tipo de dato de t_a_new: ", t_a_new)

Nuevo tipo de dato de t_a_new:  tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [14]:
t = tf.random.uniform(shape=(3, 5))
t_tr = tf.transpose(t)
print("Forma original: ", t.shape, " --> Forma transpuesta: ", t_tr.shape)

Forma original:  (3, 5)  --> Forma transpuesta:  (5, 3)


In [15]:
t = tf.zeros((30,))
t_reshape = tf.reshape(t, shape=(5, 6))
print("Nueva forma del tensor: ", t_reshape.shape)

Nueva forma del tensor:  (5, 6)


In [17]:
t = tf.zeros((1, 2, 1, 4, 1))

t_sqz = tf.squeeze(t, axis=(2, 4))
print("Forma original: ", t.shape, " --> Forma comprimida: ", t_sqz.shape)

Forma original:  (1, 2, 1, 4, 1)  --> Forma comprimida:  (1, 2, 4)


In [20]:
tf.random.set_seed(1)

t1 = tf.random.uniform(shape=(5, 2), minval=-1.0, maxval=1.0)
t2 = tf.random.normal(shape=(5, 2), mean=0.0, stddev=1.0)

t3 = tf.multiply(t1, t2).numpy()
print("Resultado de la multiplicacion", t3)

Resultado de la multiplicacion [[-0.26996338 -0.87363994]
 [-0.01652772 -0.17496566]
 [-0.296179   -0.13944866]
 [-0.7272108   0.13463594]
 [-0.40087393  0.00445268]]


In [21]:
t4 = tf.math.reduce_mean(t1, axis=0)
print("Media de t1: ", t4)

Media de t1:  tf.Tensor([0.08957257 0.2074099 ], shape=(2,), dtype=float32)


In [22]:
t5 = tf.linalg.matmul(t1, t2, transpose_b=True)
print("Resultado de la multiplicacion matricial: ", t5.numpy())

Resultado de la multiplicacion matricial:  [[-1.1436033   1.1154624  -0.8695717  -0.3210435   0.8555103 ]
 [ 0.2480186  -0.19149339  0.2504958  -0.0644026  -0.3307204 ]
 [-0.47782415  0.40717956 -0.43562764  0.02238911  0.5270062 ]
 [ 0.52479297 -0.23352614  0.74080014 -0.5925749  -1.1940588 ]
 [-0.09918742  0.26019508  0.12526006 -0.46231267 -0.39642125]]


In [23]:
t = tf.random.uniform((6,))
print("Tensor original: ", t.numpy())

t_split = tf.split(t, 3)
print("Resultado dividido en 3 partes: ", [item.numpy() for item in t_split])

Tensor original:  [0.8292774  0.634228   0.5147276  0.39108086 0.5809028  0.04848182]
Resultado dividido en 3 partes:  [array([0.8292774, 0.634228 ], dtype=float32), array([0.5147276 , 0.39108086], dtype=float32), array([0.5809028 , 0.04848182], dtype=float32)]


In [25]:
A = tf.ones((3,))
B = tf.zeros((2,))

C = tf.concat([A, B], axis=0)
print("Tensor concatenado: ", C.numpy())

Tensor concatenado:  [1. 1. 1. 0. 0.]


In [26]:
A = tf.ones((3, ))
B = tf.zeros((3, ))

S = tf.stack([A, B], axis=1)
print("Tensor apilado: ", S.numpy())


Tensor apilado:  [[1. 0.]
 [1. 0.]
 [1. 0.]]
